### ISSUE TITLE
[BACKEND] Basic SQL database

### ISSUE THREAD

**Issue by danpg94** [danpg94/space_missions#23]
Implement SQL database for storing space mission ideas.

**Comment by molki3** [comment]
### Entity Relationship Diagram
![Space_Mission  Diagrama ER](https://github.com/danpg94/space_missions/assets/54428156/258f4a12-75f8-4396-8639-fa5cde01bebf)

**Comment by danpg94** [comment]
If we were to update our page to add more elements to be stored, is it difficult to change the entity relationship diagram to fit our needs? Will there be data loss if we make these changes?

I don't remember much about my database classes :P

**Comment by molki3** [comment]
For the first question: no, is not. It's not difficult to change it.
For the second question: no, it will not. The theory says that if the attribute is declared as null, it will be able updated.

**Comment by Gabo-Puck** [comment]
Have you done any advances on this? @molki3 
I would like to help with the models and migrations in django

**Comment by molki3** [comment]
Yes, I have. Actually, I coded a signup and login system prototype for django using the same design we did in Space Mission (JUST TO UNDERSTAND THE FRAMEWORK). I have not started to code with mission's models yet, but I think it is a good progress.
Has anyone else done any implementation in django?

**Comment by molki3** [comment]
If we implement this prototype, we have to do some changes in forms and pages design, more personalization in the backend with messages and I could implement the changes for the models and database. I would like to show you this and talk about it.

**Comment by danpg94** [comment]
We reviewed this on call and proceeded merge these changes into week-4
