### ISSUE TITLE
[MOCKUP] Sumbit & View space missions

### ISSUE THREAD

**Issue by Hsm49** [danpg94/space_missions#25]
Link de los diseños:
https://www.figma.com/file/xs2mdcTfZ5BRqgmmGKE9n1/Space-Missions?type=design&node-id=0%3A1&mode=design&t=V7BnY6pzUVbMtGek-1

Mockup para la pagina "Subir misión"
![image](https://github.com/danpg94/space_missions/assets/100962574/5d0edcd2-9e84-46ef-909c-ccd61435623f)

Mockup para la página "Ver mision"
![image](https://github.com/danpg94/space_missions/assets/100962574/385d278f-8ef6-44eb-9d6f-4fa288bff090)

**Comment by molki3** [comment]
Me gusta, es un diseño limpio y queda con el diseño de la base de datos.

**Comment by angelbep2035** [comment]
Yo pensaría que si estas proponiendo un nuevo fondo en la página "Misiones Espaciales", también debería cambiar en "Agregar Misión Espacial", ya que tiene el mismo que el menú principal

**Comment by danpg94** [comment]
Closing this issue after merging 25-mockup-sumbit-view-space-missions branch into this week's milestone branch (week-3)
