### ISSUE TITLE
[FRONTEND] Update "index page"

### ISSUE THREAD

**Issue by angelbep2035** [danpg94/space_missions#26]
This is a issue that i want to update to the workspace
![image](https://github.com/danpg94/space_missions/assets/101238265/2ee15f6a-1554-4285-b617-a6f7a7c88166)

**Comment by angelbep2035** [comment]
![image](https://github.com/danpg94/space_missions/assets/101238265/3c1840de-2799-4af0-a49d-5f4a88888797)
This is the first part of my issue, i just need to solve the space travel function, i don't know why it doesn't response

**Comment by Hsm49** [comment]
The information is now displaying correctly
The "Status" part was missing, so the js code was returning an error
![image](https://github.com/danpg94/space_missions/assets/100962574/6944e9de-be6d-46e7-8bf4-590d6f26a78d)
