### ISSUE TITLE
[MOCKUP] Contacts page

### ISSUE THREAD

**Issue by Hsm49** [danpg94/space_missions#30]
Figma project:
https://www.figma.com/file/xs2mdcTfZ5BRqgmmGKE9n1/Space-Missions?type=design&node-id=0%3A1&mode=design&t=hyABlArlv167igJo-1

**Comment by Hsm49** [comment]
First mockup design for the new contact page, what do you think?
![image](https://github.com/danpg94/space_missions/assets/100962574/6def9f04-994f-4662-9a61-0e0f8cf03f2a)
The idea is that you can go to the git profile of each member when you click over their image

**Comment by Hsm49** [comment]
This is the new design for the Contacts page now available on the issue 30's branch.
![image](https://github.com/danpg94/space_missions/assets/100962574/e4cc9718-be71-4739-9cf3-62a97df2aa45)
![image](https://github.com/danpg94/space_missions/assets/100962574/c7367bbc-9de1-4175-aa22-404c4fe2e503)

**Comment by danpg94** [comment]
This looks really good! Creating a pull request for this. Noticed that issue #35 is also addressed here
