### ISSUE TITLE
[FRONTEND] Inconsistent styles

### ISSUE THREAD

**Issue by Hsm49** [danpg94/space_missions#33]
Modify the inconsistent style pages to have the same style

**Comment by Hsm49** [comment]
Modified the css styles to be consistent between them
Index page
![image](https://github.com/danpg94/space_missions/assets/100962574/fc2197c4-b1b6-46f6-80a4-8befb636d061)

Add mission page
![image](https://github.com/danpg94/space_missions/assets/100962574/ca1cdf3c-e894-45b1-b7a6-bff46d93a6bc)

View mission page
![image](https://github.com/danpg94/space_missions/assets/100962574/c5d1fdba-fd5c-4e16-8821-3cab21add398)

**Comment by danpg94** [comment]
Closing this since this was also addressed in #30
