### ISSUE TITLE
[FRONTEND] Update HTML, CSS and JS files in django version of the page

### ISSUE THREAD

**Issue by danpg94** [danpg94/space_missions#36]
[TBD]

**Comment by Hsm49** [comment]
Applied styles to the createMissions page:
![image](https://github.com/danpg94/space_missions/assets/100962574/fa1c3c53-3279-471b-ace8-8fe1d3a8fee4)

**Comment by Hsm49** [comment]
Applied styles to viewMissions page, now the rocket animation is available
![image](https://github.com/danpg94/space_missions/assets/100962574/5c7d2f59-d9be-4e83-b1b2-a775f08f1b9d)

**Comment by Hsm49** [comment]
Applied styles to the index page
![image](https://github.com/danpg94/space_missions/assets/100962574/ee7beb78-3978-4332-b65c-3227f1d97c91)

**Comment by Hsm49** [comment]
Modified index page to show a different message depending on the authentication

When is authenticated:
![image](https://github.com/danpg94/space_missions/assets/100962574/7fc4694b-786c-4c18-8e8c-a800bce2975e)

When is not authenticated:
![image](https://github.com/danpg94/space_missions/assets/100962574/63818002-527d-4d7a-9b0b-98ae4d7a91a2)

**Comment by Hsm49** [comment]
Created styles for the Sign in and Sign up pages:
![image](https://github.com/danpg94/space_missions/assets/100962574/03f37a9b-b402-4312-ad15-adbc8a14c543)

![image](https://github.com/danpg94/space_missions/assets/100962574/8fda6dfa-3b7e-4af2-89f4-ac534d4792be)

**Comment by Hsm49** [comment]
Applied styles and updated the Contacts page
![image](https://github.com/danpg94/space_missions/assets/100962574/76886ee3-c0f8-4072-a071-30797cae04f8)

**Comment by danpg94** [comment]
While testing locally, I noticed that the landing page is not showing ISS info, probably a bug due to me not running the server in WSL. Can we verify this?

![image](https://github.com/danpg94/space_missions/assets/46697843/7a6bb137-e027-46e4-97e2-2bfaf0a12891)

**Comment by danpg94** [comment]
After further disscusion, we think it is a bug not related to the issue at hand. We are continuing with the merge.
