### ISSUE TITLE
[DEVOPS] Create ANSIBLE script

### ISSUE THREAD

**Issue by danpg94** [danpg94/space_missions#41]
[TBD]

**Comment by ElBetoso** [comment]
Configured ansible.cfg file:
![image](https://github.com/danpg94/space_missions/assets/108848743/f85d9d03-0ab6-4881-9ba3-735e99839d2c)
Note(Uncomment the remote_user and private_key_file lines)

**Comment by ElBetoso** [comment]
Configured inventory file:
![image](https://github.com/danpg94/space_missions/assets/108848743/4ecaf5e3-b978-476a-b263-0fa3df336ae7)

**Comment by ElBetoso** [comment]
Test the connection:
![image](https://github.com/danpg94/space_missions/assets/108848743/92444274-83c4-4461-b1bc-9c4540ec257f)

**Comment by danpg94** [comment]
merge created
